version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: barber-shop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: barber
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: nguyentrungtinh/barber-shop-backend:${IMAGE_TAG}
    container_name: barber-shop-backend
    ports:
      - "8081:8081"
    depends_on:
      - mysql

volumes:
  mysql_data:
